### ISSUE TITLE
Saves average faces with holes in them

### ISSUE THREAD

**Issue by sashavor** [johnwmillr/Facer#14]
For some combinations of images, the average face that gets saved has a hole, usually around the mouth area:
![image](https://user-images.githubusercontent.com/14205986/215107374-8dce3d3d-ae49-48ec-8a74-63c8fdbd9072.png)
![image](https://user-images.githubusercontent.com/14205986/215107395-165d63f3-c55f-47a7-a0e2-5dc1190d078e.png)

Any idea what this may be due to?

Thanks for your amazing work!

**Comment by johnwmillr** [comment]
That's an odd bug you're running into, I'm not sure off the top of my head might be causing it. I assume there aren't any sorts of black boxes in the source images? Could you attach or provide a link to an example set of images that causes the issue?

**Comment by sashavor** [comment]
[cleaner.zip](https://github.com/johnwmillr/Facer/files/10531326/cleaner.zip)
Here you go! The holes aren't in the original images, no.
But maybe it's because it can't find the mouth landmark in one or more images?
